"""empty message

Revision ID: 006792db997f
Revises: db14107ea37e
Create Date: 2018-10-16 15:04:45.305604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006792db997f'
down_revision = 'db14107ea37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_id', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_id')
    # ### end Alembic commands ###
